#@RsvParty_HostAddress = https://rsvparty.jocandlew.com
@RsvParty_HostAddress = http://localhost:5012/

###
GET {{RsvParty_HostAddress}}/Rsvp/
Accept: application/json

###

GET {{RsvParty_HostAddress}}/Rsvp/243d55f3-8a93-486f-b3b7-de428c539deb
Accept: application/json

###

DELETE {{RsvParty_HostAddress}}/Rsvp/d23226d1-388a-417c-9343-8f2b8598190b
Accept: application/json

###

POST {{RsvParty_HostAddress}}/Rsvp/
Accept: application/json
Content-Type: application/json

{
  "Name": "Test 6",
  "NumberInParty": 1,
  "MoveGuess": "Bob film?",
  "Email": "Jer@gmail.xoc",
  "getUpdates": false,
  "getReminder": true
}

###

POST {{RsvParty_HostAddress}}/Register
Accept: application/json
Content-Type: application/json

{


  "Email": "Jonnybgood@gmail.com",
  "Password": "12345678"
  }

